//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.MyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pynct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pynct()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int IdPynct { get; set; }
        public string Gorod { get; set; }
        public string Ylica { get; set; }
        public string Dom { get; set; }
        public string Address
        {
            get
            {
                if (Gorod == null)
                    return "Не выбран пункт выдачи";
                return "Город " + Gorod + " Улица " + Ylica + " Дом " + Dom;
            }
            set
            {
                this.Address = value;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
